workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - signing_credentials
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          keychain add-certificates
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Prepare export options
        script: |
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.vinreportauto.vin</key>
              <string>Vin Ad Hoc Distribution Profile</string>
            </dict>
            <key>teamID</key>
            <string>9FLXXGGRC5</string>
          </dict>
          </plist>
          EOF
      - name: Export IPA
        script: |
          xcode-project use-profiles
          flutter build ipa --release --export-options-plist ios/ExportOptions.plist
artifacts:
  - build/ios/ipa/*.ipa
